version: "3.8"

services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_REGION=${AWS_REGION}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    networks:
      - app-network
networks:
  app-network:
    external: true      
