version: "3.8"

services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3010:3010"
      - "9229:9229"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - AWS_REGION=${AWS_REGION}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
